### ISSUE TITLE
'perform_rtsp_auth' is not defined

### ISSUE THREAD

**Issue by MyAdler** [tektengu/rtsp_authgrinder#4]
Whenever I try running this script I get the following traceback:

Traceback (most recent call last):
  File "rtsp_authgrind.py", line 400, in <module>
    test_auth_and_run()
  File "rtsp_authgrind.py", line 342, in test_auth_and_run
    perform_rtsp_auth(user, password, creator)
NameError: global name 'perform_rtsp_auth' is not defined

I am no python developer but it seems perform_rtsp_auth is out of scope and it expects different inputs than are being supplied on line 342.

**Comment by markcoker** [comment]
This ONLY does BASIC auth right now. You are most likely are needing DIGEST. (check out readme/script)
